name: Debug FTP Connection
on: workflow_dispatch

jobs:
  debug-ftp:
    runs-on: ubuntu-latest
    steps:
      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Test FTP Connection and List Files
        run: |
          echo "Tentando conectar em ftp.vilela.eng.br..."
          lftp -c "open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ftp.vilela.eng.br; ls; cd public_html; ls; cd applouvor; ls"
